name = "prompts-wallpapers"
compatibility_date = "2024-10-01"

[env.production]
# KV namespace binding
[[env.production.kv_namespaces]]
binding = "DB"
id = "your-kv-namespace-id-here" # Replace with actual KV namespace ID

# Environment variables for admin credentials
[env.production.vars]
ADMIN_USER = "admin"
ADMIN_PASS = "your-secure-password-here"

[env.preview]
# KV namespace binding for preview
[[env.preview.kv_namespaces]]
binding = "DB"
id = "your-preview-kv-namespace-id-here"

# Environment variables for admin credentials
[env.preview.vars]
ADMIN_USER = "admin"
ADMIN_PASS = "admin123"

# Pages configuration
pages_build_output_dir = "."
